image: docker:latest

services:
  - docker:dind

stages:
  - Build image
  - Push to Docker Hub

build:
  stage: build
  except:
    - master
  script:
    - docker info
    - docker build -t leberrem/ovh_exporter .

build-master:
  stage: build
  only:
    - master
  script:
    - docker info
    - docker build -t leberrem/ovh_exporter .
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push leberrem/ovh_exporter
