image: docker:latest

services:
  - docker:dind

stages:
  - Build image
  - Push to Docker Hub

docker build:
  stage: Build image
  script:
  - docker info
  - docker build -t ovh_exporter .

docker push:
  stage: Push to Docker Hub
  only:
  - master
  script:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"
  - docker push leberrem/ovh_exporter
