image: docker:latest

services:
  - docker:dind

stages:
  - Build image
  - Push to Docker Hub

docker build:
  stage: Build image
  script:
  - docker info
  - docker build -t leberrem/ovh_exporter .

docker push:
  stage: Push to Docker Hub
  only:
  - master
  script:
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push leberrem/ovh_exporter
